name: Mirroring a GitLab

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to GitLab
        run: |
          git push --force https://adrian1_daw2:${{ secrets.GITLAB_PASSWORD }}@handmadegames.org/adrian1_daw2/pathfinderai.git refs/heads/*:refs/heads/*
          git push --force --tags https://adrian1_daw2:${{ secrets.GITLAB_PASSWORD }}@handmadegames.org/adrian1_daw2/pathfinderai.git